# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!

#This file is autogenerated by /Users/development/LocalDevelopment/scratch/AWS-Tkt/backend/lambda_layer/bin/get_lambda_layer_hashes.py

#This file -WAS- autogenerated on 2025-01-08 20:54:07.501754-05:00

lambda_layer_hashes = {    {"AWSTkt-backend-dev_psycopg2_arm64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg2-pandas_amd64:1", "sha256_hex": "14be7a5a950089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0"}},
    {"AWSTkt-backend-dev_psycopg2-pandas_arm64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg2-pandas_arm64:1", "sha256_hex": "14be7a5a950089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0"}},
    {"AWSTkt-backend-dev_psycopg3_arm64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg2_amd64:1", "sha256_hex": "b8f99f26e0627a6ddec9ec87a037395cfa4f12b81e637f639ad2bfb80282cc8e"}},
    {"AWSTkt-backend-dev_psycopg3-pandas_arm64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg2_arm64:1", "sha256_hex": "b8f99f26e0627a6ddec9ec87a037395cfa4f12b81e637f639ad2bfb80282cc8e"}},
    {"AWSTkt-backend-dev_psycopg2_amd64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg3-pandas_amd64:1", "sha256_hex": "bee0f0557991c26bd7cbce31b66840a78504b7e35b65558cfe132f4ab4bcc266"}},
    {"AWSTkt-backend-dev_psycopg2-pandas_amd64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg3-pandas_arm64:1", "sha256_hex": "bee0f0557991c26bd7cbce31b66840a78504b7e35b65558cfe132f4ab4bcc266"}},
    {"AWSTkt-backend-dev_psycopg3_amd64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg3_amd64:1", "sha256_hex": "a9919dc9339b309429e4e68654f3717267d06306d0d6aac08f2da7a452aa1daa"}},
    {"AWSTkt-backend-dev_psycopg3-pandas_amd64": {"arn": "arn:aws:lambda:us-east-1:127516845550:layer:AWSTkt-backend-dev_psycopg3_arm64:1", "sha256_hex": "a9919dc9339b309429e4e68654f3717267d06306d0d6aac08f2da7a452aa1daa"}},
}

# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
