# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!

#This file is autogenerated by /Users/development/LocalDevelopment/scratch/AWS-Tkt/backend/lambda_layer/bin/get_lambda_layer_hashes.py

#This file -WAS- autogenerated on 2025-01-09 12:00:08.300600-05:00

### ================================================================================

lambda_layer_hashes :dict[str, dict[str, any]] = {
    'dev' : {
    },
    'XYZtier' : {
        "NoSuchProject-NoSuchTier_psycopg2_arm64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg2-pandas_amd64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg2-pandas_arm64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg2-pandas_arm64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg3_arm64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg2_amd64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg3-pandas_arm64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg2_arm64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg2_amd64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg3-pandas_amd64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg2-pandas_amd64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg3-pandas_arm64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg3_amd64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg3_amd64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "NoSuchProject-NoSuchTier_psycopg3-pandas_amd64" : { "arn" : "arn:aws:lambda:ap-northeast-2:123456789012:layer:NoSuchProject-NoSuchTier_psycopg3_arm64:1", "sha256_hex" : "06dd0848250089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
    },
}

# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
