# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!

#This file is autogenerated by /Users/development/LocalDevelopment/CTF-CloudOne/CancerTrialsFinder-CloudOne/backend/lambda_layer/bin/get_lambda_layer_hashes.py

#This file -WAS- autogenerated on 2025-06-12 11:22:25.284191-04:00

### ================================================================================

lambda_layer_hashes :dict[str, dict[str, any]] = {
    'matt2' : {
        "CTF-backend-matt2_psycopg2_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg2_arm64:1", "sha256_hex" : "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d" },
        "CTF-backend-matt2_psycopg-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg-pandas_arm64:1", "sha256_hex" : "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165" },
        "CTF-backend-matt2_psycopg3_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3_arm64:2", "sha256_hex" : "3c244766e42763ad51d00e451f2a225eb76b14cf417d31d32d3f90d3a5bffe47" },
        "CTF-backend-matt2_psycopg3-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3-pandas_arm64:2", "sha256_hex" : "c22d5f7dbdaea2f11e308a8b09dad1d7bb8d0001007a3df2484f44c1efcb5daa" },
        "CTF-backend-matt2_numpy_etc_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_numpy_etc_arm64:2", "sha256_hex" : "fe13820ee89014440eb52bf91b20b0f778ba39a2d745e045aacea24da087f12f" },
        "CTF-backend-matt2_psycopg2_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg2_amd64:1", "sha256_hex" : "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d" },
        "CTF-backend-matt2_psycopg-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg-pandas_amd64:1", "sha256_hex" : "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165" },
        "CTF-backend-matt2_psycopg3_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3_amd64:2", "sha256_hex" : "3c244766e42763ad51d00e451f2a225eb76b14cf417d31d32d3f90d3a5bffe47" },
        "CTF-backend-matt2_psycopg3-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3-pandas_amd64:2", "sha256_hex" : "c22d5f7dbdaea2f11e308a8b09dad1d7bb8d0001007a3df2484f44c1efcb5daa" },
        "CTF-backend-matt2_numpy_etc_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_numpy_etc_amd64:2", "sha256_hex" : "fe13820ee89014440eb52bf91b20b0f778ba39a2d745e045aacea24da087f12f" },
        "CTF-backend-matt2_weasy_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_weasy_amd64:1", "sha256_hex" : "c43eaf2c26e1c5609fceb2b924557d77f8c76f241550cab39c9a8897cc979f4c" },
        "CTF-backend-matt2_weasy_pypi_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_weasy_pypi_amd64:1", "sha256_hex" : "58803e71d19612a637f9f07f7ed8b2c63387f8651d85cd4fa1471c9c1893ca9b" },
    },
    'matt3': {
        "CTF-backend-matt2_psycopg2_arm64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg2_arm64:1",
            "sha256_hex": "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d"},
        "CTF-backend-matt2_psycopg-pandas_arm64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg-pandas_arm64:1",
            "sha256_hex": "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165"},
        "CTF-backend-matt2_psycopg3_arm64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3_arm64:2",
            "sha256_hex": "3c244766e42763ad51d00e451f2a225eb76b14cf417d31d32d3f90d3a5bffe47"},
        "CTF-backend-matt2_psycopg3-pandas_arm64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3-pandas_arm64:2",
            "sha256_hex": "c22d5f7dbdaea2f11e308a8b09dad1d7bb8d0001007a3df2484f44c1efcb5daa"},
        "CTF-backend-matt2_numpy_etc_arm64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_numpy_etc_arm64:2",
            "sha256_hex": "fe13820ee89014440eb52bf91b20b0f778ba39a2d745e045aacea24da087f12f"},
        "CTF-backend-matt2_psycopg2_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg2_amd64:1",
            "sha256_hex": "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d"},
        "CTF-backend-matt2_psycopg-pandas_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg-pandas_amd64:1",
            "sha256_hex": "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165"},
        "CTF-backend-matt2_psycopg3_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3_amd64:2",
            "sha256_hex": "3c244766e42763ad51d00e451f2a225eb76b14cf417d31d32d3f90d3a5bffe47"},
        "CTF-backend-matt2_psycopg3-pandas_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_psycopg3-pandas_amd64:2",
            "sha256_hex": "c22d5f7dbdaea2f11e308a8b09dad1d7bb8d0001007a3df2484f44c1efcb5daa"},
        "CTF-backend-matt2_numpy_etc_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_numpy_etc_amd64:2",
            "sha256_hex": "fe13820ee89014440eb52bf91b20b0f778ba39a2d745e045aacea24da087f12f"},
        "CTF-backend-matt2_weasy_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_weasy_amd64:1",
            "sha256_hex": "c43eaf2c26e1c5609fceb2b924557d77f8c76f241550cab39c9a8897cc979f4c"},
        "CTF-backend-matt2_weasy_pypi_amd64": {
            "arn": "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-matt2_weasy_pypi_amd64:1",
            "sha256_hex": "58803e71d19612a637f9f07f7ed8b2c63387f8651d85cd4fa1471c9c1893ca9b"},
    },
    'dev' : {
        "CTF-backend-dev_psycopg2_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg2_arm64:1", "sha256_hex" : "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d" },
        "CTF-backend-dev_psycopg-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg-pandas_arm64:1", "sha256_hex" : "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165" },
        "CTF-backend-dev_psycopg3_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg3_arm64:1", "sha256_hex" : "eef605d661d25b06802701791e7ba46322b42ad9b6152161a5069831b534883d" },
        "CTF-backend-dev_psycopg3-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg3-pandas_arm64:1", "sha256_hex" : "10687d310e047e590ba9e741105726d7218cab16299fe3edaa148b4c7b9bca7f" },
        "CTF-backend-dev_numpy_etc_arm64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_numpy_etc_arm64:1", "sha256_hex" : "73b3599ff56e7cf4b7444af3a681b1aab27c97204bbfd105c73ded8ee6c5bad4" },
        "CTF-backend-dev_psycopg2_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg2_amd64:1", "sha256_hex" : "dddaeee7a7bb26d57aecfc9574a1136a6395e1c1e83d59c8968c249ae657043d" },
        "CTF-backend-dev_psycopg-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg-pandas_amd64:1", "sha256_hex" : "da34e9734e0920949317a439769a2be9df43e97b40c4b92e199d7b96949e5165" },
        "CTF-backend-dev_psycopg3_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg3_amd64:1", "sha256_hex" : "eef605d661d25b06802701791e7ba46322b42ad9b6152161a5069831b534883d" },
        "CTF-backend-dev_psycopg3-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_psycopg3-pandas_amd64:1", "sha256_hex" : "10687d310e047e590ba9e741105726d7218cab16299fe3edaa148b4c7b9bca7f" },
        "CTF-backend-dev_numpy_etc_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_numpy_etc_amd64:1", "sha256_hex" : "73b3599ff56e7cf4b7444af3a681b1aab27c97204bbfd105c73ded8ee6c5bad4" },
        "CTF-backend-dev_weasy_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_weasy_amd64:1", "sha256_hex" : "c43eaf2c26e1c5609fceb2b924557d77f8c76f241550cab39c9a8897cc979f4c" },
        "CTF-backend-dev_weasy_pypi_amd64" : { "arn" : "arn:aws:lambda:us-east-1:924221118260:layer:CTF-backend-dev_weasy_pypi_amd64:1", "sha256_hex" : "58803e71d19612a637f9f07f7ed8b2c63387f8651d85cd4fa1471c9c1893ca9b" },
    },
    'sarma' : {
        "CTF-backend-sarma_psycopg2_arm64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg2_arm64:3", "sha256_hex" : "c5684b521c5aac54a19f34670f6b03091d3a2cb047f159027138ad020e56bdff" },
        "CTF-backend-sarma_psycopg-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg-pandas_arm64:3", "sha256_hex" : "14be7a5a950089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "CTF-backend-sarma_psycopg3_arm64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg3_arm64:3", "sha256_hex" : "a9919dc9339b309429e4e68654f3717267d06306d0d6aac08f2da7a452aa1daa" },
        "CTF-backend-sarma_psycopg3-pandas_arm64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg3-pandas_arm64:3", "sha256_hex" : "ec2dd1fd8010399c7369b6a75113786971c7a66720237ecb94c81512c8ead40d" },
        "CTF-backend-sarma_numpy_etc_arm64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_numpy_etc_arm64:3", "sha256_hex" : "e25b824e310f143bc39d41b4b51d18bd3859507d3aed96996636d4f23239f356" },
        "CTF-backend-sarma_psycopg2_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg2_amd64:1", "sha256_hex" : "c5684b521c5aac54a19f34670f6b03091d3a2cb047f159027138ad020e56bdff" },
        "CTF-backend-sarma_psycopg-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg-pandas_amd64:1", "sha256_hex" : "14be7a5a950089d9b4af44e326106dd0848246bec0bbf4c808f60ce05cdbf7b0" },
        "CTF-backend-sarma_psycopg3_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg3_amd64:1", "sha256_hex" : "a9919dc9339b309429e4e68654f3717267d06306d0d6aac08f2da7a452aa1daa" },
        "CTF-backend-sarma_psycopg3-pandas_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_psycopg3-pandas_amd64:1", "sha256_hex" : "ec2dd1fd8010399c7369b6a75113786971c7a66720237ecb94c81512c8ead40d" },
        "CTF-backend-sarma_numpy_etc_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_numpy_etc_amd64:1", "sha256_hex" : "e25b824e310f143bc39d41b4b51d18bd3859507d3aed96996636d4f23239f356" },
        "CTF-backend-sarma_weasy_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-sarma_weasy_amd64:1", "sha256_hex" : "e25b824e310f143bc39d41b4b51d18bd3859507d3aed96996636d4f23239f356" },
        "CTF-backend-dev_weasy_pypi_amd64" : { "arn" : "arn:aws:lambda:us-east-1:127516845550:layer:CTF-backend-dev_weasy_pypi_amd64:1", "sha256_hex" : "e25b824e310f143bc39d41b4b51d18bd3859507d3aed96996636d4f23239f356" },
    },
}

# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!! do --NOT-- edit this file  !!!!!!!!!!!!!!!!!!!!!!!!!
