4,5c4,5
< ENTERPRISE_NAME = "NIH-NCI"
< HUMAN_FRIENDLY_APP_NAME = "FACTrial"
---
> ENTERPRISE_NAME = "EssexMgmt"
> HUMAN_FRIENDLY_APP_NAME = "AWS-Ticket"
7c7
< CDK_APP_NAME = "FACT"
---
> CDK_APP_NAME = "AWSTkt"
