AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31

Description: >
  AWS SAM project for lambda named 'wipeout-bucket'
  See README.md for details on how to use this AWS-SAM template.

Parameters:
  Tier:
    Type: String
    Description: dev | int | uat | prod | some-developer-branch

  EnterpriseName:
    Type: String
    Description: >-
        !! ATTENTION !! LowerCase
        See project's git-repo's constants.py file for further details
    Default: "nih-nci"  ### Used in bucket-name.  So, must be 100% lower-case!!!
    AllowedPattern: "^[a-z0-9-]+$"

  AppName:
    Type: String
    Description: >-
        See project's git-repo's constants.py file for further details
    Default: "CTF"

  AppNameLowerCase:
    Type: String
    Description: >-
        !! ATTENTION !! LowerCase
        See project's git-repo's constants.py file for further details
    Default: "ctf"
    AllowedPattern: "^[a-z0-9-]+$"

  ApplnGroupName:
    Type: String
    Description: >-
        This is mandatory for organizing multiple 𝜆s into one App (under Application-section of 𝜆-console)
    Default: "CTF"

  DateTimeStamp:
    Description: Date & Time
    Type: String
    # AllowedPattern: >-
    #   [0-9]-[0-9][0-9]-[0-9][0-9]
    #   [0-9]:[0-9][0-9]:[0-9][0-9]
    AllowedPattern: >-
      ^\d{4}(-\d{2}){2}T(\d{2}:){2}\d{2}$
    ConstraintDescription: "Date and time of STACK-creation"


Globals:
  ### https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  ### More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

  Function:

    Tags:
      'ApplicationName': !Ref ApplnGroupName  ### This is mandatory for organizing multiple 𝜆s into one App (under Application-section of 𝜆-console)

    Timeout: 900
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true


Conditions:
  IsValidTier: !Or
    - !Equals [!Ref Tier, "dev"]
    - !Equals [!Ref Tier, "int"]
    - !Equals [!Ref Tier, "uat"]
    - !Equals [!Ref Tier, "prod"]



Resources: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html

  MyLambdaFuncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}"
      Description: !Sub >-
        Role for 'wipeout-bucket' Lambda-function created by Stack ${AWS::StackName} on ${DateTimeStamp}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        # - AmazonS3FullAccess ### Warning: To make this Lambda be usable across ALL projects, enable this (avoid the next line below)
        - PolicyName: !Sub "${AWS::StackName}-s3-delete"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "ListAllBucketsNeedsAllAccess"
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                  - "s3:ListAllMyBuckets"
                Resource:
                  - "*"
              - Sid: "S3AccessNeededByWipeOutBucketLambda"
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                  - "s3:DeleteBucket"
                  - "s3:DeleteBucketPolicy"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectTagging"
                  - "s3:DeleteObjectVersion"
                  - "s3:DeleteObjectVersionTagging"
                  - "s3:GetObject"
                  - "s3:GetObjectTagging"
                  - "s3:GetObjectAttributes"
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectVersionTagging"
                  - "s3:GetObjectVersionAttributes"
                  - "s3:ListBucketMultipartUploads"
                Resource:
                  - !Sub "arn:aws:s3:::${AppNameLowerCase}-*"
                  - !Sub "arn:aws:s3:::${AppNameLowerCase}-*/*"
                  - !Sub "arn:aws:s3:::${EnterpriseName}-${AppNameLowerCase}-*"
                  - !Sub "arn:aws:s3:::${EnterpriseName}-${AppNameLowerCase}-*/*"
      Tags:
        - Key: PRODUCT
          Value: 'factrial' ### CRRI rules.  Must be all lowercase.
        - Key: VERSION
          Value: 'v2.0.0'   ### CRRI rules.  Must be all lowercase.
        - Key: Environment
          Value: !If [IsValidTier, !Ref Tier, 'dev']
        # Environment: !Sub '${Tier}-${ApplnGroupName}'  ### This is mandatory for organizing multiple 𝜆s into one App (under Application-section of 𝜆-console)
        - Key: application
          Value: !Ref AppName
        - Key: component
          Value: 'devops'
        - Key: env
          Value: !Ref Tier
        - Key: branch
          Value: 'main'
        - Key: BUILD
          Value: !Ref DateTimeStamp
        - Key: SOURCE
          Value: "https://github.com/BIAD/cloud_eng.git/AWS-SAM/lambdas/wipeout-bucket/"

  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  MyLambdaFunc:
    Type: AWS::Serverless::Function
        ### More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
        ### More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      ### FunctionName: !Sub wipeout-bucket-${Tier}
      Description: >-
        Delete all objects in the Bucket specified via `event` parameter of Handler, and then destroy the bucket also
      CodeUri: ./src/
      Handler: app.lambdaHandler
      Role: !GetAtt MyLambdaFuncRole.Arn
      Runtime: nodejs20.x
      Architectures:
        - arm64
      # Powertools env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsRDSInstanceSetup
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        ApplicationName: !Ref ApplnGroupName  ### This is mandatory for organizing multiple 𝜆s into one App (under Application-section of 𝜆-console)
        PRODUCT: 'factrial' ### CRRI rules.  Must be all lowercase.
        VERSION: 'v2.0.0'   ### CRRI rules.  Must be all lowercase.
        ENVIRONMENT: !If [IsValidTier, !Ref Tier, 'dev']
        # Environment: !Sub '${Tier}-${ApplnGroupName}'  ### This is mandatory for organizing multiple 𝜆s into one App (under Application-section of 𝜆-console)
        application: !Ref AppName
        component: 'devops'
        env: !Ref Tier
        branch: 'main'
        BUILD: !Ref DateTimeStamp
        SOURCE: "https://github.com/BIAD/cloud_eng.git/AWS-SAM/lambdas/wipeout-bucket/"

      # Events:
      #   invoke:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /call
      #       Method: get

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts


  # ### The Applications section of the Lambda-console includes a Monitoring tab where ..
  # ###   .. you can review an Amazon CloudWatch dashboard with aggregate metrics for the resources in your application.
  # ### https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/using-sam-cli-init.html#using-sam-cli-init-new-insights
  # ApplicationResourceGroup:
  #   Type: AWS::ResourceGroups::Group
  #   Properties:
  #     Name:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-${CDK_APP_NAME}-Tools-
  #         - Ref: Tier
  #     ResourceQuery:
  #       Type: CLOUDFORMATION_STACK_1_0
  #     Tags:
  #       - Key: PRODUCT
  #         Value: 'factrial' ### CRRI rules.  Must be all lowercase.
  #       - Key: VERSION
  #         Value: 'v2.0.0'   ### CRRI rules.  Must be all lowercase.
  #       - Key: ENVIRONMENT
  #         Value: !If [IsValidTier, !Ref Tier, 'dev']
  #       - Key: ENVIRONMENT
  #         Value: !Sub '${Tier}'
  #       - Key: application
  #         Value: !Ref AppName
  #       - Key: component
  #         Value: 'devops'
  #       - Key: env
  #         Value: !Sub '${Tier}'
  #       - Key: branch
  #         Value: 'main'
  #       - Key: BUILD
  #         Value: !Sub "${DateTimeStamp}"
  #       - Key: SOURCE
  #         Value: "https://github.com/BIAD/cloud_eng.git/AWS-SAM/lambdas/wipeout-bucket/"

  # ApplicationInsightsMonitoring:
  #   Type: AWS::ApplicationInsights::Application
  #   ### https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html
  #   Properties:
  #     ResourceGroupName:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-${CDK_APP_NAME}-Tools-
  #         - Ref: Tier
  #     AutoConfigurationEnabled: 'true'
  #     Tags:
  #       - Key: PRODUCT
  #         Value: 'factrial' ### CRRI rules.  Must be all lowercase.
  #       - Key: VERSION
  #         Value: 'v2.0.0'   ### CRRI rules.  Must be all lowercase.
  #       - Key: ENVIRONMENT
  #         Value: !If [IsValidTier, !Ref Tier, 'dev']
  #       - Key: ENVIRONMENT
  #         Value: !Sub '${Tier}'
  #       - Key: application
  #         Value: !Ref AppName
  #       - Key: component
  #         Value: 'devops'
  #       - Key: env
  #         Value: !Sub '${Tier}'
  #       - Key: branch
  #         Value: 'main'
  #       - Key: BUILD
  #         Value: !Sub "${DateTimeStamp}"
  #       - Key: SOURCE
  #         Value: "https://github.com/BIAD/cloud_eng.git/AWS-SAM/lambdas/wipeout-bucket/"
  #   DependsOn: ApplicationResourceGroup


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # MyApi:
  #   Description: API Gateway endpoint URL for Prod stage for Lambda-function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/call/"
  MyLambdaFunc:
    Description: Lambda Function ARN
    Value: !GetAtt MyLambdaFunc.Arn
  MyLambdaFuncIamRole:
    Description: AWS-SAM-created Implicit IAM-Role created for Lambda-function
    Value: !GetAtt MyLambdaFuncRole.Arn
